#!/usr/bin/sh

# Autostart
pgrep -x sxhkd > /dev/null || sxhkd &
xrandr --rate 60 &
feh --bg-fill --randomize ~/Wallpapers/ &
picom &
~/.config/polybar/launch.sh &
~/mousesettings.sh &

# Workspaces
bspc monitor -d 1 2 3 4 5

# Windows
bspc config border_width         0
bspc config window_gap          16
bspc config split_ratio          0.50
