#! /bin/sh

#Autostart
pgrep -x sxhkd > /dev/null || sxhkd &

#Workspaces
bspc monitor -d 1 2 3 4 5

#Windows
bspc config border_width         0
bspc config window_gap          16
bspc config split_ratio          0.5

